# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 07:08


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_blog_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/%Y/%m/%d'),
        ),
    ]
