# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iaas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='iaas id')),
                ('name', models.CharField(max_length=20, verbose_name='iaas name')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='server id')),
                ('name', models.CharField(max_length=50, verbose_name='server name')),
                ('cpu_type', models.CharField(max_length=20, verbose_name='cpu type')),
                ('cpu_core', models.IntegerField(default=1, verbose_name='cpu core number')),
                ('os_type', models.CharField(max_length=20, verbose_name='os type')),
                ('disk_type', models.CharField(default='general', max_length=20, verbose_name='disk type: ssd | general')),
                ('disk_size', models.IntegerField(verbose_name='disk size')),
                ('inner_ip', models.CharField(max_length=20, verbose_name='inner ip')),
                ('outer_ip', models.CharField(max_length=20, verbose_name='outer ip')),
                ('created_date', models.DateTimeField(verbose_name='date server created')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='zone id')),
                ('name', models.CharField(max_length=20, verbose_name='zone name')),
            ],
        ),
    ]
