# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='disk_size',
            field=models.IntegerField(default=0, verbose_name='disk size'),
        ),
    ]
