# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20171213_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='iaas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Iaas', verbose_name='IAAS'),
        ),
        migrations.AddField(
            model_name='server',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Zone', verbose_name='ZONE'),
        ),
        migrations.AddField(
            model_name='zone',
            name='iaas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Iaas', verbose_name='IAAS'),
        ),
    ]
