# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20171213_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='disk_size',
            field=models.IntegerField(default=40, verbose_name='disk size'),
        ),
        migrations.AlterField(
            model_name='server',
            name='disk_type',
            field=models.CharField(choices=[('general', 'general disk'), ('ssd', 'ssd disk')], default='general', max_length=20, verbose_name='disk type'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_type',
            field=models.CharField(choices=[('centos', 'centos system'), ('ubuntu', 'ubuntu system')], default='centos', max_length=50, verbose_name='os type'),
        ),
    ]
