# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_auto_20171213_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='instance id')),
                ('name', models.CharField(max_length=50, verbose_name='instance name')),
                ('cpu_type', models.CharField(choices=[('Intel Xeon CPU', 'Entry Level'), ('Intel Xeon Platinum 8163', 'General Level'), ('Intel Xeon E5-2682v4', 'Enhance Level'), ('Intel Xeon Gold 6149', 'Supreme Level')], default='Intel Xeon CPU', max_length=50, verbose_name='cpu type')),
                ('cpu_core', models.IntegerField(choices=[(1, '1 Core'), (2, '2 Core'), (4, '4 Core'), (8, '8 Core')], default=1, verbose_name='cpu core number')),
                ('os_type', models.CharField(choices=[('centos', 'centos system'), ('ubuntu', 'ubuntu system')], default='centos', max_length=50, verbose_name='os type')),
                ('disk_type', models.CharField(choices=[('general', 'general disk'), ('ssd', 'ssd disk')], default='general', max_length=20, verbose_name='disk type')),
                ('disk_size', models.IntegerField(default=40, verbose_name='disk size')),
                ('inner_ip', models.CharField(max_length=20, verbose_name='inner ip')),
                ('outer_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='outer ip')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date server created')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='region id')),
                ('name', models.CharField(max_length=20, verbose_name='region name')),
            ],
        ),
        migrations.RemoveField(
            model_name='server',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='iaas',
        ),
        migrations.AddField(
            model_name='iaas',
            name='sp',
            field=models.CharField(choices=[('aliyun', 'aliyun'), ('ucloud', 'ucloud'), ('qingcloud', 'qingcloud'), ('aws', 'aws'), ('juliye', 'juliye')], default='juliye', max_length=20, verbose_name='iaas provider'),
        ),
        migrations.AlterField(
            model_name='iaas',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='iaas account name'),
        ),
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.AddField(
            model_name='region',
            name='iaas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Iaas', verbose_name='IAAS'),
        ),
        migrations.AddField(
            model_name='instance',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Zone', verbose_name='ZONE'),
        ),
        migrations.AddField(
            model_name='zone',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Region', verbose_name='REGION'),
        ),
    ]
